### ISSUE TITLE
Rotation Offset

### ISSUE THREAD

**Issue by miro-ux** [SpeciesFileGroup/svg_radial_menu#1]
Love this menu!
Is there a way to offset the overall rotation or the starting point of the buttons?

For example the default for 4 sections is this:
![image](https://user-images.githubusercontent.com/7188826/135369815-0f2d185c-342d-4074-8ba3-c7ec46ff95b6.png)

How do I go about making the following but with the text properly oriented?
![image](https://user-images.githubusercontent.com/7188826/135369906-20e72e72-1f9d-4959-a029-c81b01242b95.png)
Thank you!

**Comment by miro-ux** [comment]
After digging around I was able to achieve it by adding the offset to `radiusStart` and `radiusEnd` in `slice.ts`

![image](https://user-images.githubusercontent.com/7188826/135380171-950ba959-fbfb-4b0c-a926-a859f89a98b3.png)


```
this.radiusStart = radiusStart + (180/4)
this.radiusEnd = radiusStart + radiusSlice  + (180/4)
```
Where `4` is the number of slices. (Could be + or - )

No idea how to not hard code it but would love to see this implemented somehow ☺️

**Comment by jlpereira** [comment]
Hello @miro-ux 

Thanks for use our library. I will implement your request for the next update. You will be able to set the rotation angle in options object

**Comment by jlpereira** [comment]
New version was released. You can set `rotateAngle` now. Take a look at README.md, there is another changes related with the defualt SVG attributes that maybe you will need to change in your configuration.
